[package]
name = "rs-sdk"
version = "0.25.0-dev"
edition = "2021"

description = "Dash Platform Software Development Kit for Rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dapi-grpc = { path = "../dapi-grpc", features = [
    "platform",
], default-features = false }
drive = { path = "../rs-drive", features = [
    "verify",
], default-features = false }
delegate = { version = "0.9.0" }
thiserror = { version = "1.0.39" }
mockall = { version = "0.11", optional = true }
tokio = { version = "1.28", features = ["rt-multi-thread"], optional = true }
tonic = { version = "0.9.2", features = [
    "codegen",
    "prost",
], default-features = false, optional = true }
url = {}
async-trait = { version = "0.1.68", optional = true }
[features]

default = ["mockall", "client", "core"]
mockall = ["drive/mockall", "dep:mockall"]
client = ["dep:tokio", "dep:tonic", "dep:async-trait", "dapi-grpc/client"]
core = ["dapi-grpc/core"]
