[package]
name = "rs-drive-light-client-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]

rs-drive-light-client = { path = "../rs-drive-light-client", features = [
    "bindgen",
] }
