[package]
name = "rs-drive-verify-c-binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "drive"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = { version = "0.24.3" }

[dependencies]
hex = { version = "0.4.3" }
dpp = { path = "../rs-dpp" }

[dependencies.drive]
path = "../rs-drive"
features = ["verify"]
default-features = false
